import { useEffect, useState } from 'react'
import { architectureApi } from '../../api/architectureApiClient'
import type { DiscoveryRunSummary, ProductCompositionView, ProductView } from '../../api/architectureApiTypes'

export function ProductWorkspace({workspaceId,onStatus}:{workspaceId:string;onStatus:(s:string)=>void}) {
 const [products,setProducts]=useState<ProductView[]>([]),[selected,setSelected]=useState<ProductView|null>(null),[composition,setComposition]=useState<ProductCompositionView|null>(null)
 const [runs,setRuns]=useState<DiscoveryRunSummary[]>([]),[name,setName]=useState(''),[source,setSource]=useState(''),[runId,setRunId]=useState(''),[moduleName,setModuleName]=useState('')
 useEffect(()=>{if(!workspaceId){setProducts([]);setSelected(null);return} Promise.all([architectureApi.listProducts(workspaceId),architectureApi.listDiscoveryRuns(workspaceId)]).then(([p,r])=>{setProducts(p);setRuns(r);setSelected(p[0]??null)}).catch(e=>onStatus(String(e)))},[workspaceId])
 function update(p:ProductView){setSelected(p);setProducts(x=>x.map(v=>v.productId===p.productId?p:v))}
 async function create(){const p=await architectureApi.createProduct(workspaceId,{name,description:'',actorRef:'ui-user'});setProducts(x=>[...x,p]);setSelected(p);setName('')}
 async function addRepo(){if(!selected)return;update(await architectureApi.addProductRepository(workspaceId,selected.productId,{sourceIdentity:source,sourceReference:source,role:'SERVICE',discoveryRunIds:runId?[runId]:[],versionMetadata:{},ownershipMetadata:{},actorRef:'ui-user'}));setSource('')}
 async function addModule(){if(!selected)return;update(await architectureApi.createProductModule(workspaceId,selected.productId,{name:moduleName,description:'',type:'APPLICATION',actorRef:'ui-user'}));setModuleName('')}
 return <div className="product-workspace">
  <section className="panel"><div className="section-heading"><div><h2>Products</h2><p>Compose repository evidence without architectural judgement.</p></div><div className="form-row"><input placeholder="Product name" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name} onClick={()=>create().catch(e=>onStatus(String(e)))}>Create</button></div></div><div className="list compact-list">{products.map(p=><button className={'list-item '+(selected?.productId===p.productId?'selected':'')} onClick={()=>{setSelected(p);setComposition(null)}} key={p.productId}><strong>{p.name}</strong><span>{p.repositories.length} repositories · {p.modules.length} modules</span></button>)}</div></section>
  {selected&&<><section className="panel"><h2>{selected.name}: repositories</h2><div className="form-row"><input placeholder="Repository path or URI" value={source} onChange={e=>setSource(e.target.value)}/><select value={runId} onChange={e=>setRunId(e.target.value)}><option value="">No discovery run</option>{runs.map(r=><option key={r.runId} value={r.runId}>{r.sourceReference}</option>)}</select><button disabled={!source} onClick={()=>addRepo().catch(e=>onStatus(String(e)))}>Add</button></div>{selected.repositories.map(r=><article className="result-row" key={r.repositoryId}><strong>{r.sourceIdentity}</strong><p>{r.discoveryRunIds.map(id=><a key={id} href={`#discovery-run-${id}`}>{id}</a>)}</p><select value={r.moduleId??''} onChange={e=>architectureApi.assignProductRepository(workspaceId,selected.productId,e.target.value,r.repositoryId).then(update)}><option value="">Unassigned</option>{selected.modules.map(m=><option key={m.moduleId} value={m.moduleId}>{m.name}</option>)}</select></article>)}</section>
  <section className="panel"><h2>Explicit product modules</h2><div className="form-row"><input value={moduleName} onChange={e=>setModuleName(e.target.value)} placeholder="Module name"/><button disabled={!moduleName} onClick={()=>addModule().catch(e=>onStatus(String(e)))}>Add</button></div>{selected.modules.map(m=><span className="badge" key={m.moduleId}>{m.name}</span>)}</section>
  <section className="panel"><div className="section-heading"><div><h2>Evidence composition</h2><p>Exact shared identities and explicit ambiguity only.</p></div><button onClick={()=>architectureApi.composeProduct(workspaceId,selected.productId).then(setComposition).catch(e=>onStatus(String(e)))}>Compose</button></div>{composition&&<><dl className="metrics"><div><dt>Repositories</dt><dd>{composition.metrics.repositoryCount}</dd></div><div><dt>Evidence</dt><dd>{composition.metrics.evidenceCount}</dd></div><div><dt>Relationships</dt><dd>{composition.metrics.crossRepositoryRelationshipCount}</dd></div><div><dt>Conflicts</dt><dd>{composition.metrics.unresolvedIdentityCount}</dd></div></dl><h3>Relationships</h3>{composition.relationships.map(r=><article className="result-row" key={r.relationshipId}><strong>{r.type}</strong><p>{r.description}</p><small>Evidence: {r.productEvidenceIds.join(', ')}</small></article>)}<h3>Identity conflicts</h3>{composition.conflicts.map(c=><article className="result-row" key={c.conflictId}><span className="badge warning">Unresolved</span><strong>{c.candidateValue}</strong><p>{c.explanation}</p></article>)}<h3>Repository contributions</h3>{composition.contributions.map(c=><article className="result-row" key={c.discoveryRunId}><strong>{c.sourceIdentity}</strong><p><a href={`#discovery-run-${c.discoveryRunId}`}>{c.discoveryRunId}</a> · {c.evidenceCount} evidence items</p></article>)}</>}</section></>}
 </div>
}
