package com.architectureworkbench.api;

import com.architectureworkbench.api.ApiDtos.*;
import com.architectureworkbench.audit.*;
import java.time.Instant;
import java.util.*;
import java.util.function.Predicate;

/** Composes descriptive cross-repository dependencies; it deliberately makes no risk or smell judgement. */
final class ProductDependencyAnalysisService {
 private final ProductRepositoryStore store; private final AuditSink audit;
 ProductDependencyAnalysisService(ProductRepositoryStore store,AuditSink audit){this.store=store;this.audit=audit;}

 ProductDependencyCompositionView compose(String w,String p,String actor){
  ProductModels.Product product=product(w,p); ProductCompositionView composition=store.composition(w,p).orElseThrow(()->new IllegalStateException("Compose product evidence before dependencies."));
  String correlation="product-dependencies-"+UUID.randomUUID(); emit(product,ArchitectureEventType.PRODUCT_DEPENDENCY_COMPOSITION_STARTED,actor,correlation,Map.of("productId",p));
  List<ProductDependencyView> dependencies=new ArrayList<>(); List<ContractCompatibilityView> compatibility=new ArrayList<>(); List<CompatibilityDiagnostic> diagnostics=new ArrayList<>();
  Map<String,List<ProductEvidenceItem>> contracts=group(composition.evidence(),this::contractId); Map<String,List<ProductEvidenceItem>> channels=group(composition.evidence(),this::channel);
  for(var entry:contracts.entrySet()) correlateContract(entry.getKey(),entry.getValue(),dependencies,compatibility,diagnostics);
  for(var entry:channels.entrySet()) correlateShared(entry.getKey(),entry.getValue(),"MESSAGE_CHANNEL",dependencies);
  correlateMaven(composition.evidence(),dependencies); correlateExplicitApi(composition.evidence(),dependencies);
  List<ReleaseRelationshipView> releases=releaseRelationships(product,composition.evidence());
  List<ProductDependencyView> deployments=deploymentRelationships(composition.evidence()); dependencies.addAll(deployments);
  List<OwnershipRelationshipView> ownership=ownership(product,composition.evidence(),contracts,diagnostics);
  long unknown=compatibility.stream().filter(x->x.status().equals("UNKNOWN")).count(), incompatible=compatibility.stream().filter(x->x.status().equals("INCOMPATIBLE")).count();
  long explicit=compatibility.size()-unknown; double coverage=compatibility.isEmpty()?0:Math.round(explicit*10000d/compatibility.size())/100d;
  var metrics=new ProductDependencyMetrics(dependencies.size(),count(dependencies,"API_CONTRACT"),count(dependencies,"EVENT_CONTRACT"),count(dependencies,"COMMAND_CONTRACT"),count(dependencies,"MAVEN_ARTIFACT")+count(dependencies,"SHARED_LIBRARY"),count(dependencies,"MESSAGE_CHANNEL"),coverage,(int)unknown,(int)incompatible,releases.size(),(int)releases.stream().filter(x->x.type().equals("RELEASE_BUNDLE")||x.type().equals("SHARED_RELEASE_VERSION")).count(),deployments.size(),(int)ownership.stream().filter(x->x.type().equals("OWNERSHIP_CONFLICT")).count(),(int)ownership.stream().filter(x->x.type().equals("OWNERLESS_CONTRACT")).count());
  long version=store.dependencyCompositions(w,p).stream().mapToLong(ProductDependencyCompositionView::compositionVersion).max().orElse(0)+1;
  List<String> runIds=composition.contributions().stream().map(RepositoryEvidenceContribution::discoveryRunId).distinct().toList();
  var result=new ProductDependencyCompositionView(p,w,version,Instant.now(),correlation,runIds,List.copyOf(dependencies),List.copyOf(compatibility),releases,deployments,ownership,graph(product,dependencies),metrics,List.copyOf(diagnostics));
  store.saveDependencyComposition(w,p,result);
  emit(product,ArchitectureEventType.PRODUCT_COMPATIBILITY_EVALUATED,actor,correlation,Map.of("productId",p,"relationshipCount",String.valueOf(compatibility.size())));
  emit(product,ArchitectureEventType.PRODUCT_COMPOSITION_VERSION_CREATED,actor,correlation,Map.of("productId",p,"compositionVersion",String.valueOf(version)));
  emit(product,ArchitectureEventType.PRODUCT_DEPENDENCY_COMPOSITION_COMPLETED,actor,correlation,Map.of("productId",p,"dependencyCount",String.valueOf(dependencies.size()))); return result;
 }
 ProductDependencyCompositionView latest(String w,String p){product(w,p);return store.dependencyComposition(w,p).orElseThrow(()->new NoSuchElementException("Product dependency composition not generated: "+p));}
 List<ProductDependencyCompositionView> versions(String w,String p){product(w,p);return store.dependencyCompositions(w,p);}
 List<ProductDependencyView> dependencies(String w,String p,String type,String repo,String compatibility,double minimumConfidence){return latest(w,p).dependencies().stream().filter(x->blank(type)||x.dependencyType().equalsIgnoreCase(type)).filter(x->blank(repo)||x.sourceRepositoryId().equals(repo)||x.targetRepositoryId().equals(repo)).filter(x->blank(compatibility)||x.compatibilityStatus().equalsIgnoreCase(compatibility)).filter(x->x.confidence()>=minimumConfidence).toList();}

 private void correlateContract(String id,List<ProductEvidenceItem> items,List<ProductDependencyView> out,List<ContractCompatibilityView> compatibility,List<CompatibilityDiagnostic> diagnostics){
  List<ProductEvidenceItem> producers=items.stream().filter(this::producer).toList(),consumers=items.stream().filter(this::consumer).toList();
  for(var a:producers)for(var b:consumers)if(!a.repositoryId().equals(b.repositoryId())){
   String av=version(a),bv=version(b),status=av.isBlank()||bv.isBlank()?"UNKNOWN":av.equals(bv)?"COMPATIBLE":"INCOMPATIBLE"; double confidence=Math.min(a.evidence().confidence().value(),b.evidence().confidence().value()); String type=contractType(a,b);
   var refs=refs(a,b);String derivation="Exact contract identity '"+id+"' connects an explicit producer and consumer across repositories.";
   var d=new ProductDependencyView("dependency-"+out.size(),type,"SOURCE_TO_TARGET","OBSERVED",a.repositoryId(),b.repositoryId(),id,av,bv,status,confidence,"OBSERVED",derivation,refs);out.add(d);
   var c=new ContractCompatibilityView("compatibility-"+compatibility.size(),a.repositoryId(),b.repositoryId(),id,av,bv,status,status.equals("UNKNOWN")?"One or both sides lack a literal version.":status.equals("COMPATIBLE")?"Producer and consumer declare the same literal version.":"Producer and consumer declare different literal versions.",confidence,refs);compatibility.add(c);
   if(!status.equals("COMPATIBLE"))diagnostics.add(new CompatibilityDiagnostic("compatibility-diagnostic-"+diagnostics.size(),status.equals("INCOMPATIBLE")?"ERROR":"INFO",status,c.explanation(),List.of(a.repositoryId(),b.repositoryId()),refs.stream().map(DependencyEvidenceReference::evidenceId).toList()));
  }
  if(producers.isEmpty()||consumers.isEmpty()) correlateShared(id,items,contractType(items.get(0),items.get(0)),out);
 }
 private void correlateShared(String id,List<ProductEvidenceItem> items,String type,List<ProductDependencyView> out){List<ProductEvidenceItem> unique=items.stream().filter(distinctByRepo()).toList();for(int i=0;i<unique.size();i++)for(int j=i+1;j<unique.size();j++){var a=unique.get(i);var b=unique.get(j);out.add(new ProductDependencyView("dependency-"+out.size(),type,"SHARED","OBSERVED",a.repositoryId(),b.repositoryId(),id,version(a),version(b),"NOT_APPLICABLE",Math.min(a.evidence().confidence().value(),b.evidence().confidence().value()),"OBSERVED","Both repositories reference the same exact technical identity.",refs(a,b)));}}
 private void correlateMaven(List<ProductEvidenceItem> items,List<ProductDependencyView> out){var published=items.stream().filter(x->x.evidence().type().equals("maven-module")).toList();var used=items.stream().filter(x->x.evidence().type().contains("maven-dependency")).toList();for(var p:published)for(var u:used)if(!p.repositoryId().equals(u.repositoryId())&&sameCoordinate(p,u)){out.add(new ProductDependencyView("dependency-"+out.size(),"MAVEN_ARTIFACT","SOURCE_TO_TARGET","OBSERVED",p.repositoryId(),u.repositoryId(),coordinate(p),version(p),version(u),literalCompatibility(version(p),version(u)),Math.min(p.evidence().confidence().value(),u.evidence().confidence().value()),"OBSERVED","A Maven dependency matches an artifact produced by another Product repository.",refs(p,u)));}}
 private void correlateExplicitApi(List<ProductEvidenceItem> items,List<ProductDependencyView> out){var exposed=items.stream().filter(x->x.evidence().attributes().containsKey("operationId")&&(x.evidence().type().contains("openapi")||x.evidence().type().contains("endpoint"))).toList();var called=items.stream().filter(x->x.evidence().attributes().containsKey("operationId")&&(x.evidence().attributes().containsKey("consumer")||x.evidence().attributes().containsKey("caller"))).toList();for(var a:exposed)for(var b:called)if(!a.repositoryId().equals(b.repositoryId())&&a.evidence().attributes().get("operationId").equals(b.evidence().attributes().get("operationId")))out.add(new ProductDependencyView("dependency-"+out.size(),"API_CONTRACT","SOURCE_TO_TARGET","OBSERVED",a.repositoryId(),b.repositoryId(),a.evidence().attributes().get("operationId"),version(a),version(b),literalCompatibility(version(a),version(b)),Math.min(a.evidence().confidence().value(),b.evidence().confidence().value()),"OBSERVED","Exact OpenAPI operation id connects an exposed API and caller.",refs(a,b)));}
 private List<ReleaseRelationshipView> releaseRelationships(ProductModels.Product product,List<ProductEvidenceItem> evidence){var out=new ArrayList<ReleaseRelationshipView>();for(int i=0;i<product.repositories().size();i++)for(int j=i+1;j<product.repositories().size();j++){var a=product.repositories().get(i);var b=product.repositories().get(j);String av=first(a.versionMetadata().get("version"),a.versionMetadata().get("releaseVersion")),bv=first(b.versionMetadata().get("version"),b.versionMetadata().get("releaseVersion"));String ab=first(a.versionMetadata().get("releaseBundle"),a.versionMetadata().get("stream")),bb=first(b.versionMetadata().get("releaseBundle"),b.versionMetadata().get("stream"));if(!ab.isBlank()&&ab.equals(bb))out.add(new ReleaseRelationshipView("release-"+out.size(),"RELEASE_BUNDLE",a.id().value(),b.id().value(),"Repositories are explicitly associated with release bundle "+ab+".",av,bv,1,List.of()));else if(!av.isBlank()&&av.equals(bv))out.add(new ReleaseRelationshipView("release-"+out.size(),"SHARED_RELEASE_VERSION",a.id().value(),b.id().value(),"Repositories declare the same release version "+av+".",av,bv,1,List.of()));}return List.copyOf(out);}
 private List<ProductDependencyView> deploymentRelationships(List<ProductEvidenceItem> items){var out=new ArrayList<ProductDependencyView>();List<ProductEvidenceItem> deployment=items.stream().filter(x->{String t=x.evidence().type().toLowerCase();return t.contains("deployment")||t.contains("infrastructure")||t.contains("database")||t.contains("environment");}).toList();Map<String,List<ProductEvidenceItem>> grouped=group(deployment,x->first(x.evidence().attributes().get("resourceName"),x.evidence().attributes().get("stackName"),x.evidence().attributes().get("databaseName"),x.evidence().attributes().get("environment")));for(var e:grouped.entrySet())correlateShared(e.getKey(),e.getValue(),"ENVIRONMENT_CONFIGURATION",out);return out;}
 private List<OwnershipRelationshipView> ownership(ProductModels.Product product,List<ProductEvidenceItem> evidence,Map<String,List<ProductEvidenceItem>> contracts,List<CompatibilityDiagnostic> diagnostics){var out=new ArrayList<OwnershipRelationshipView>();Map<String,String> owners=new LinkedHashMap<>();for(var r:product.repositories()){String owner=first(r.ownershipMetadata().get("owner"),r.ownershipMetadata().get("team"));if(!owner.isBlank())owners.put(r.id().value(),owner);}for(int i=0;i<product.repositories().size();i++)for(int j=i+1;j<product.repositories().size();j++){String a=owners.get(product.repositories().get(i).id().value()),b=owners.get(product.repositories().get(j).id().value());if(a!=null&&a.equals(b))out.add(new OwnershipRelationshipView("ownership-"+out.size(),"SAME_OWNER",product.repositories().get(i).id().value(),product.repositories().get(j).id().value(),a,"Repositories explicitly declare the same owner.",1,List.of()));}for(var e:contracts.entrySet()){Set<String> declared=e.getValue().stream().map(x->first(x.evidence().attributes().get("declaredOwner"),x.evidence().attributes().get("owner"))).filter(x->!x.isBlank()).collect(java.util.stream.Collectors.toCollection(LinkedHashSet::new));if(declared.isEmpty())out.add(new OwnershipRelationshipView("ownership-"+out.size(),"OWNERLESS_CONTRACT",e.getValue().get(0).repositoryId(),"","","No explicit owner was found for contract "+e.getKey()+".",1,refs(e.getValue().get(0))));else if(declared.size()>1)out.add(new OwnershipRelationshipView("ownership-"+out.size(),"OWNERSHIP_CONFLICT",e.getValue().get(0).repositoryId(),"",String.join(", ",declared),"Conflicting explicit owners were found for contract "+e.getKey()+".",1,e.getValue().stream().map(this::ref).toList()));}return List.copyOf(out);}
 private ProductDependencyGraph graph(ProductModels.Product p,List<ProductDependencyView> ds){var nodes=new ArrayList<DependencyGraphNode>();for(var r:p.repositories()){String owner=first(r.ownershipMetadata().get("owner"),r.ownershipMetadata().get("team"));nodes.add(new DependencyGraphNode(r.id().value(),"REPOSITORY",r.sourceIdentity(),r.id().value(),r.moduleId()==null?"":r.moduleId().value(),owner));}var edges=ds.stream().map(d->new DependencyGraphEdge(d.dependencyId(),d.sourceRepositoryId(),d.targetRepositoryId(),d.dependencyType(),d.technicalIdentity(),d.compatibilityStatus(),d.confidence(),d.evidence().stream().map(DependencyEvidenceReference::evidenceId).toList())).toList();return new ProductDependencyGraph(nodes,edges);}
 private Map<String,List<ProductEvidenceItem>> group(List<ProductEvidenceItem> xs,java.util.function.Function<ProductEvidenceItem,String> key){Map<String,List<ProductEvidenceItem>> m=new LinkedHashMap<>();for(var x:xs){String k=key.apply(x);if(!k.isBlank())m.computeIfAbsent(k,z->new ArrayList<>()).add(x);}return m;}
 private String contractId(ProductEvidenceItem x){return first(x.evidence().attributes().get("contractId"),x.evidence().attributes().get("eventName"),x.evidence().attributes().get("commandName"));} private String channel(ProductEvidenceItem x){return first(x.evidence().attributes().get("channelName"),x.evidence().attributes().get("queueName"),x.evidence().attributes().get("topicName"),x.evidence().attributes().get("busName"));}
 private boolean producer(ProductEvidenceItem x){return x.evidence().type().contains("producer")||x.evidence().attributes().containsKey("producer")||"publish".equalsIgnoreCase(x.evidence().attributes().get("operation"));} private boolean consumer(ProductEvidenceItem x){return x.evidence().type().contains("consumer")||x.evidence().attributes().containsKey("consumer")||"subscribe".equalsIgnoreCase(x.evidence().attributes().get("operation"));}
 private String contractType(ProductEvidenceItem a,ProductEvidenceItem b){if(a.evidence().attributes().containsKey("eventName")||b.evidence().attributes().containsKey("eventName"))return "EVENT_CONTRACT";if(a.evidence().attributes().containsKey("commandName")||b.evidence().attributes().containsKey("commandName"))return "COMMAND_CONTRACT";return "API_CONTRACT";}
 private String version(ProductEvidenceItem x){return first(x.evidence().attributes().get("contractVersion"),x.evidence().attributes().get("version"),x.evidence().attributes().get("schemaVersion"),x.evidence().attributes().get("apiVersion"));} private String literalCompatibility(String a,String b){return a.isBlank()||b.isBlank()?"UNKNOWN":a.equals(b)?"COMPATIBLE":"INCOMPATIBLE";}
 private boolean sameCoordinate(ProductEvidenceItem a,ProductEvidenceItem b){return !artifact(a).isBlank()&&artifact(a).equals(artifact(b))&&(groupId(a).isBlank()||groupId(b).isBlank()||groupId(a).equals(groupId(b)));} private String artifact(ProductEvidenceItem x){return x.evidence().attributes().getOrDefault("artifactId","");}private String groupId(ProductEvidenceItem x){return x.evidence().attributes().getOrDefault("groupId","");}private String coordinate(ProductEvidenceItem x){return groupId(x)+":"+artifact(x);}
 private java.util.function.Predicate<ProductEvidenceItem> distinctByRepo(){Set<String>s=new HashSet<>();return x->s.add(x.repositoryId());}
 private List<DependencyEvidenceReference> refs(ProductEvidenceItem...xs){return Arrays.stream(xs).map(this::ref).toList();} private DependencyEvidenceReference ref(ProductEvidenceItem x){var e=x.evidence();return new DependencyEvidenceReference(x.repositoryId(),x.discoveryRunId(),x.productEvidenceId(),e.evidenceId(),e.attributes().getOrDefault("pluginId",""),e.provenance().repositoryRelativeFilePath(),e.provenance().symbol());}
 private ProductModels.Product product(String w,String p){return store.find(w,p).orElseThrow(()->new NoSuchElementException("Product not found: "+p));}private static boolean blank(String x){return x==null||x.isBlank();}private static String first(String...xs){for(String x:xs)if(!blank(x))return x;return "";}private static int count(List<ProductDependencyView>x,String t){return (int)x.stream().filter(d->d.dependencyType().equals(t)).count();}
 private void emit(ProductModels.Product p,ArchitectureEventType t,String actor,String correlation,Map<String,String> payload){audit.append(new ArchitectureEventEnvelope(null,t,p.workspaceId(),ArchitectureEventSource.PRODUCT_COMPOSITION_SERVICE,Actor.system(blank(actor)?"product-service":actor),CausationId.newId("product-dependency-command"),new CorrelationId(correlation),null,AuditRelevance.REQUIRED,MutationTarget.NEITHER,payload,null));}
}
