package com.architectureworkbench.api;

import com.architectureworkbench.api.ApiDtos.*;
import com.architectureworkbench.audit.*;
import java.time.Instant;
import java.util.*;

/** Deterministically converts findings into governed options; it never mutates Product or graph state. */
final class ProductArchitectureRecommendationService {
 private final ProductRepositoryStore store; private final AuditSink audit;
 ProductArchitectureRecommendationService(ProductRepositoryStore store,AuditSink audit){this.store=store;this.audit=audit;}

 ProductRecommendationGenerationView generate(String w,String p,String actor){
  var product=requireProduct(w,p);var analysis=store.architectureAnalysis(w,p).orElseThrow(()->new IllegalStateException("Run Product architecture analysis before generating recommendations."));
  String generationId="recommendation-generation-"+UUID.randomUUID(),correlation="product-recommendations-"+UUID.randomUUID();Instant now=Instant.now();
  emit(product,ArchitectureEventType.PRODUCT_RECOMMENDATION_GENERATION_STARTED,actor,correlation,Map.of("productId",p,"analysisId",analysis.analysisId()));
  List<ProductArchitectureRecommendationView> prior=history(w,p);List<ProductArchitectureRecommendationView> generated=new ArrayList<>();
  for(var finding:analysis.findings())generated.add(fromFinding(w,p,analysis,finding,prior,now));
  if(generated.isEmpty()||analysis.assessment().evidenceCoverage()<50)generated.add(furtherDiscovery(w,p,analysis,prior,now));
  var result=new ProductRecommendationGenerationView(generationId,p,analysis.analysisId(),analysis.compositionVersion(),correlation,now,List.copyOf(generated),analysis.diagnostics().stream().map(ProductArchitectureAnalysisDiagnostic::message).toList());
  store.saveRecommendationGeneration(w,p,result);for(var r:generated)emit(product,ArchitectureEventType.PRODUCT_RECOMMENDATION_GENERATED,actor,correlation,Map.of("productId",p,"recommendationId",r.recommendationId(),"category",r.category()));return result;
 }

 List<ProductArchitectureRecommendationView> list(String w,String p,String category,String concern,String priority,String horizon,String status,String repository,String module,String confidence,String finding){requireProduct(w,p);return history(w,p).stream().filter(x->blank(category)||x.category().equalsIgnoreCase(category)).filter(x->blank(concern)||x.concerns().contains(concern)).filter(x->blank(priority)||x.priority().equalsIgnoreCase(priority)).filter(x->blank(horizon)||x.timeHorizon().equalsIgnoreCase(horizon)).filter(x->blank(status)||x.status().equalsIgnoreCase(status)).filter(x->blank(repository)||x.repositoryIds().contains(repository)).filter(x->blank(module)||x.moduleIds().contains(module)).filter(x->blank(confidence)||x.confidence().equalsIgnoreCase(confidence)).filter(x->blank(finding)||x.supportingFindingIds().contains(finding)).toList();}
 ProductArchitectureRecommendationView get(String w,String p,String id){return history(w,p).stream().filter(x->x.recommendationId().equals(id)).reduce((a,b)->b).orElseThrow(()->new NoSuchElementException("Recommendation not found: "+id));}
 List<ProductRecommendationGenerationView> generations(String w,String p){requireProduct(w,p);return store.recommendationGenerations(w,p);}
 ProductArchitectureRecommendationView transition(String w,String p,String id,String status,RecommendationActionRequest request){var old=get(w,p,id);var updated=copy(old,status,old.reviewSessionId(),old.proposedChangeId(),Instant.now());replace(w,p,updated);emit(requireProduct(w,p),ArchitectureEventType.PRODUCT_RECOMMENDATION_STATUS_CHANGED,request==null?null:request.actorRef(),"recommendation-status-"+UUID.randomUUID(),Map.of("productId",p,"recommendationId",id,"status",status));return updated;}
 ProductArchitectureRecommendationView submitReview(String w,String p,String id,RecommendationActionRequest request){var old=get(w,p,id);String review="review-session-"+UUID.randomUUID();var updated=copy(old,"UNDER_REVIEW",review,old.proposedChangeId(),Instant.now());replace(w,p,updated);emit(requireProduct(w,p),ArchitectureEventType.PRODUCT_RECOMMENDATION_SUBMITTED_FOR_REVIEW,request==null?null:request.actorRef(),"recommendation-review-"+UUID.randomUUID(),Map.of("productId",p,"recommendationId",id,"reviewSessionId",review));return updated;}
 RecommendationProposedChangeView createProposedChange(String w,String p,String id,RecommendationActionRequest request){var old=get(w,p,id);String change="product-proposed-change-"+UUID.randomUUID();var updated=copy(old,old.status(),old.reviewSessionId(),change,Instant.now());replace(w,p,updated);return new RecommendationProposedChangeView(change,id,"PROPOSED","Proposal records intent only; canonical Product and graph mutation require separate explicit acceptance.",old.supportingFindingIds(),old.evidenceIds(),Instant.now());}

 private ProductArchitectureRecommendationView fromFinding(String w,String p,ProductArchitectureAnalysisView a,ProductArchitectureFindingView f,List<ProductArchitectureRecommendationView> prior,Instant now){
  String category=category(f),key=p+"|"+category+"|"+f.repositoryIds().stream().sorted().toList()+"|"+f.moduleIds().stream().sorted().toList();var previous=prior.stream().filter(x->x.deterministicKey().equals(key)).reduce((x,y)->y);int recurrence=previous.map(x->x.recurrenceCount()+1).orElse(1);
  boolean strength=f.polarity().equals("STRENGTH");double score=Math.max(.2,f.confidenceScore()-(f.counterEvidence().isEmpty()?0:.1));String priority=priority(f,score,strength),horizon=horizon(category,priority,strength),effort=effort(category),impact=impact(f);
  List<RecommendationAlternativeView> alternatives=alternatives(category,f,strength);String title=strength?"Preserve and govern: "+f.title():title(category);
  return new ProductArchitectureRecommendationView("product-recommendation-"+UUID.randomUUID(),key,p,w,a.analysisId(),a.compositionVersion(),title,category,"CANDIDATE",priority,horizon,confidence(score),score,List.of(f.concern()),List.of(f.findingId()),f.indicators().stream().map(ProductArchitectureIndicatorView::indicatorId).toList(),f.supportingEvidenceIds(),f.repositoryIds(),f.moduleIds(),f.counterEvidence(),strength?"The analysis identified a supported modularity strength. Retention and monitoring are valid options.":"This candidate responds to finding '"+f.title()+"' while preserving its uncertainty and counter-evidence.",alternatives,impact,effort,List.of("Change may introduce migration and operational complexity.","Validate the option against delivery constraints before acceptance."),List.of("Confirm ownership and delivery capacity.","Validate affected contract and deployment consumers."),List.of(strength?"The healthy pattern remains explicit and measurable.":"Reduce the coordination surface identified by the finding."),List.of("Re-run Product analysis after implementation.","No regression in explicit compatibility or deployment independence."),f.limitations(),recurrence,previous.map(ProductArchitectureRecommendationView::recommendationId).orElse(""),"","",now,now);
 }
 private ProductArchitectureRecommendationView furtherDiscovery(String w,String p,ProductArchitectureAnalysisView a,List<ProductArchitectureRecommendationView> prior,Instant now){String key=p+"|FURTHER_DISCOVERY";var previous=prior.stream().filter(x->x.deterministicKey().equals(key)).reduce((x,y)->y);return new ProductArchitectureRecommendationView("product-recommendation-"+UUID.randomUUID(),key,p,w,a.analysisId(),a.compositionVersion(),"Gather missing Product delivery evidence","FURTHER_DISCOVERY","CANDIDATE","MEDIUM","NEAR_TERM","LOW",.45,List.of("GOVERNANCE"),a.findings().stream().map(ProductArchitectureFindingView::findingId).toList(),List.of(),a.findings().stream().flatMap(x->x.supportingEvidenceIds().stream()).distinct().toList(),List.of(),List.of(),List.of(),"Evidence coverage is insufficient for a confident structural recommendation.",List.of(new RecommendationAlternativeView("discover-delivery","Inspect release and deployment evidence","Identify deployment sequencing, release history, database ownership, and actual customer Product compositions.","MEDIUM","LOW","LOW","LOW",List.of(),List.of(),"Products with partial discovery",.8)),"MEDIUM","LOW",List.of("Analysis remains inconclusive until evidence is collected."),List.of("Repository owners can supply missing evidence."),List.of("Evidence coverage improves."),List.of("Coverage exceeds 70%."),List.of("No structural change is recommended from insufficient evidence."),previous.map(x->x.recurrenceCount()+1).orElse(1),previous.map(ProductArchitectureRecommendationView::recommendationId).orElse(""),"","",now,now);}
 private List<RecommendationAlternativeView> alternatives(String c,ProductArchitectureFindingView f,boolean strength){if(strength)return List.of(option("retain","Retain and document the current pattern","Keep the current architecture, document why it is intentional, and monitor the supporting metric.","LOW","LOW",.9));return switch(c){case "DEPENDENCY_CYCLE_REDUCTION"->List.of(option("contract","Introduce a stable contract boundary","Invert one dependency behind a versioned contract.","HIGH","HIGH",.78),option("async","Replace one direction with asynchronous communication","Use an event where temporal decoupling is semantically valid.","HIGH","HIGH",.66),option("merge","Consolidate artificially separated responsibilities","Merge components when they cannot evolve independently.","MEDIUM","HIGH",.58),option("accept","Document intentional coupling","Retain temporarily with explicit ownership and review date.","LOW","LOW",.85));case "CENTRAL_ROUTER_GOVERNANCE"->List.of(option("govern","Govern a thin routing runtime","Retain domain contract ownership, externalise policies, version configuration, and preserve audit/replay.","HIGH","MEDIUM",.86),option("separate","Separate policy ownership from routing runtime","Move domain-specific policies to owning modules when coordination evidence justifies it.","HIGH","HIGH",.67),option("monitor","Monitor routing centrality","Take no structural action until coordination-load evidence increases.","LOW","LOW",.9));case "SHARED_DOMAIN_MODEL_REDUCTION"->List.of(option("owned-kernel","Formalise an owned shared kernel","Define ownership, compatibility, and release rules for genuinely shared concepts.","MEDIUM","MEDIUM",.78),option("contracts","Replace shared entities with versioned contracts","Use owned mappings or anti-corruption layers.","HIGH","HIGH",.72),option("consolidate","Consolidate inseparable modules","Reduce accidental distribution if responsibilities cannot evolve separately.","HIGH","HIGH",.55));default->List.of(option("govern","Introduce explicit governance","Make ownership, compatibility, and lifecycle rules explicit.","MEDIUM","MEDIUM",.82),option("decouple","Reduce mandatory coordination","Introduce an independently evolvable boundary where evidence and delivery economics justify it.","HIGH","HIGH",.65),option("defer","Defer and monitor","Accept the current structure with a measurable review trigger.","LOW","LOW",.88));};}
 private RecommendationAlternativeView option(String id,String title,String description,String impact,String effort,double confidence){return new RecommendationAlternativeView(id,title,description,impact,effort,effort.equals("HIGH")?"HIGH":"MEDIUM","MEDIUM",List.of("Confirm affected owners and consumers."),List.of(new RecommendationTradeoffView(description,effort+" implementation effort","Migration assumptions require validation.")),"Existing Product composition",confidence);}
 private static String category(ProductArchitectureFindingView f){String t=f.findingType();if(f.polarity().equals("STRENGTH"))return "NO_CHANGE_REQUIRED";if(t.contains("RELEASE"))return "RELEASE_DECOUPLING";if(t.contains("DEPLOYMENT"))return "DEPLOYMENT_DECOUPLING";if(t.contains("CYCLE"))return "DEPENDENCY_CYCLE_REDUCTION";if(t.contains("SHARED_DOMAIN"))return "SHARED_DOMAIN_MODEL_REDUCTION";if(t.contains("DATABASE"))return "SHARED_DATA_OWNERSHIP";if(t.contains("SYNCHRONOUS"))return "SYNCHRONOUS_COUPLING_REDUCTION";if(t.contains("ROUTER"))return "CENTRAL_ROUTER_GOVERNANCE";if(t.contains("MESSAGING"))return "MESSAGING_TOPOLOGY_GOVERNANCE";if(t.contains("PACKAGING"))return "PRODUCT_PACKAGING_DECOUPLING";if(t.contains("MODULE"))return "PRODUCT_MODULE_BOUNDARY_CLARIFICATION";if(t.contains("OWNERSHIP"))return "OWNERSHIP_CLARIFICATION";if(t.contains("CONTRACT"))return "CONTRACT_VERSIONING";return "FURTHER_DISCOVERY";}
 private static String title(String c){return switch(c){case "RELEASE_DECOUPLING"->"Evaluate independent release options";case "DEPLOYMENT_DECOUPLING"->"Reduce mandatory deployment coordination";case "DEPENDENCY_CYCLE_REDUCTION"->"Resolve the cross-repository dependency cycle";case "CENTRAL_ROUTER_GOVERNANCE"->"Govern central routing responsibility";case "CONTRACT_VERSIONING"->"Establish explicit contract versioning and compatibility";case "PRODUCT_PACKAGING_DECOUPLING"->"Make Product Module packaging dependencies explicit";default->"Evaluate "+c.toLowerCase().replace('_',' ');};}
 private static String priority(ProductArchitectureFindingView f,double confidence,boolean strength){if(strength)return "INFORMATIONAL";if(confidence<.55)return "LOW";if(f.severity().equals("CRITICAL"))return "CRITICAL";if(f.severity().equals("HIGH")&&confidence>=.75)return "HIGH";return f.severity().equals("LOW")?"LOW":"MEDIUM";}
 private static String horizon(String c,String priority,boolean strength){if(strength)return "MONITOR";if(priority.equals("CRITICAL"))return "IMMEDIATE";if(c.contains("VERSION")||c.contains("OWNERSHIP"))return "NEXT_RELEASE";if(c.contains("DATABASE")||c.contains("DOMAIN_MODEL"))return "STRATEGIC";return priority.equals("HIGH")?"NEAR_TERM":"MEDIUM_TERM";}
 private static String effort(String c){return Set.of("SHARED_DATA_OWNERSHIP","SHARED_DOMAIN_MODEL_REDUCTION","DEPENDENCY_CYCLE_REDUCTION","DEPLOYMENT_DECOUPLING").contains(c)?"HIGH":"MEDIUM";}
 private static String impact(ProductArchitectureFindingView f){return Set.of("HIGH","CRITICAL").contains(f.severity())?"HIGH":f.polarity().equals("STRENGTH")?"LOW":"MEDIUM";}
 private static String confidence(double x){return x>=.9?"CONFIRMED":x>=.75?"HIGH":x>=.55?"MEDIUM":"LOW";}
 private List<ProductArchitectureRecommendationView> history(String w,String p){return store.recommendationGenerations(w,p).stream().flatMap(x->x.recommendations().stream()).toList();}
 private void replace(String w,String p,ProductArchitectureRecommendationView value){var gs=new ArrayList<>(store.recommendationGenerations(w,p));for(int i=gs.size()-1;i>=0;i--){var g=gs.get(i);if(g.recommendations().stream().anyMatch(x->x.recommendationId().equals(value.recommendationId()))){var rs=new ArrayList<>(g.recommendations());rs.replaceAll(x->x.recommendationId().equals(value.recommendationId())?value:x);store.saveRecommendationGeneration(w,p,new ProductRecommendationGenerationView(g.generationId(),g.productId(),g.analysisId(),g.compositionVersion(),g.correlationId(),g.generatedAt(),List.copyOf(rs),g.diagnostics()));return;}}}
 private static ProductArchitectureRecommendationView copy(ProductArchitectureRecommendationView x,String status,String review,String change,Instant now){return new ProductArchitectureRecommendationView(x.recommendationId(),x.deterministicKey(),x.productId(),x.workspaceId(),x.analysisId(),x.compositionVersion(),x.title(),x.category(),status,x.priority(),x.timeHorizon(),x.confidence(),x.confidenceScore(),x.concerns(),x.supportingFindingIds(),x.supportingIndicatorIds(),x.evidenceIds(),x.repositoryIds(),x.moduleIds(),x.counterEvidence(),x.rationale(),x.alternatives(),x.impact(),x.effort(),x.risks(),x.preconditions(),x.expectedOutcomes(),x.successMeasures(),x.limitations(),x.recurrenceCount(),x.supersedesRecommendationId(),review,change,x.generatedAt(),now);}
 private ProductModels.Product requireProduct(String w,String p){return store.find(w,p).orElseThrow(()->new NoSuchElementException("Product not found: "+p));}private static boolean blank(String x){return x==null||x.isBlank();}
 private void emit(ProductModels.Product p,ArchitectureEventType type,String actor,String correlation,Map<String,String> payload){audit.append(new ArchitectureEventEnvelope(null,type,p.workspaceId(),ArchitectureEventSource.PRODUCT_COMPOSITION_SERVICE,Actor.system(blank(actor)?"product-recommendation-service":actor),CausationId.newId("product-recommendation-command"),new CorrelationId(correlation),null,AuditRelevance.REQUIRED,MutationTarget.NEITHER,payload,null));}
}
