package com.architectureworkbench.api;

import com.architectureworkbench.api.ApiDtos.*;
import com.architectureworkbench.audit.*;
import java.time.Instant;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/** Explainable, deterministic Product-level interpretation over a retained dependency composition. */
final class ProductArchitectureAnalysisService {
 private final ProductRepositoryStore store; private final AuditSink audit;
 ProductArchitectureAnalysisService(ProductRepositoryStore store,AuditSink audit){this.store=store;this.audit=audit;}

 ProductArchitectureAnalysisView analyse(String w,String p,String actor){
  var product=store.find(w,p).orElseThrow(()->new NoSuchElementException("Product not found: "+p));
  var composition=store.composition(w,p).orElseThrow(()->new IllegalStateException("Compose product evidence before architecture analysis."));
  var dependency=store.dependencyComposition(w,p).orElseThrow(()->new IllegalStateException("Compose Product dependencies before architecture analysis."));
  Instant start=Instant.now();String id="product-analysis-"+UUID.randomUUID(),correlation="product-analysis-"+UUID.randomUUID();
  emit(product,ArchitectureEventType.PRODUCT_ARCHITECTURE_ANALYSIS_STARTED,actor,correlation,Map.of("productId",p,"analysisId",id));
  List<ProductArchitectureIndicatorView> indicators=new ArrayList<>(); List<ProductArchitectureAnalysisDiagnostic> diagnostics=new ArrayList<>();
  releases(dependency,indicators); deployments(dependency,indicators); cycles(dependency,indicators); contracts(dependency,indicators);
  sharedModels(dependency,indicators); sharedDatabase(dependency,indicators); communication(dependency,indicators); router(dependency,composition,indicators);
  boundaries(product,dependency,indicators); ownership(dependency,indicators); strengths(product,dependency,indicators);
  int coverage=coverage(product,composition,dependency,diagnostics); double coverageFactor=coverage/100d;
  List<ProductArchitectureFindingView> findings=aggregate(indicators,product,dependency.compositionVersion(),coverageFactor,start);
  String classification=classify(findings,product.repositories().size(),coverage); double score=assessmentConfidence(findings,coverage);
  String confidence=confidence(score,coverage);var assessment=new ProductDistributedMonolithAssessment("distributed-monolith-"+UUID.randomUUID(),p,dependency.compositionVersion(),"COMPLETED",classification,confidence,score,coverage,List.copyOf(indicators),ids(findings,f->f.polarity().equals("STRENGTH")),ids(findings,f->f.polarity().equals("RISK")),List.copyOf(diagnostics),diagnostics.stream().flatMap(d->d.missingEvidence().stream()).distinct().toList(),Instant.now());
  var result=new ProductArchitectureAnalysisView(id,p,w,dependency.compositionVersion(),diagnostics.isEmpty()?"COMPLETED":"PARTIALLY_COMPLETED",start,Instant.now(),correlation,findings,assessment,List.copyOf(diagnostics));
  store.saveArchitectureAnalysis(w,p,result);
  for(var finding:findings)emit(product,ArchitectureEventType.PRODUCT_ARCHITECTURE_FINDING_CREATED,actor,correlation,Map.of("productId",p,"analysisId",id,"findingId",finding.findingId(),"findingType",finding.findingType()));
  emit(product,ArchitectureEventType.PRODUCT_DISTRIBUTED_MONOLITH_ASSESSMENT_COMPLETED,actor,correlation,Map.of("productId",p,"analysisId",id,"classification",classification));
  emit(product,ArchitectureEventType.PRODUCT_ARCHITECTURE_ANALYSIS_COMPLETED,actor,correlation,Map.of("productId",p,"analysisId",id,"findingCount",String.valueOf(findings.size())));return result;
 }
 ProductArchitectureAnalysisView latest(String w,String p){requireProduct(w,p);return store.architectureAnalysis(w,p).orElseThrow(()->new NoSuchElementException("Product architecture analysis not generated: "+p));}
 List<ProductArchitectureAnalysisView> history(String w,String p){requireProduct(w,p);return store.architectureAnalyses(w,p);}
 ProductArchitectureAnalysisView get(String w,String p,String id){return history(w,p).stream().filter(a->a.analysisId().equals(id)).findFirst().orElseThrow(()->new NoSuchElementException("Analysis not found: "+id));}
 List<ProductArchitectureFindingView> findings(String w,String p,String analysis,String concern,String type,String severity,String confidence,String repository,String module,String polarity){return get(w,p,analysis).findings().stream().filter(x->blank(concern)||x.concern().equalsIgnoreCase(concern)).filter(x->blank(type)||x.findingType().equalsIgnoreCase(type)).filter(x->blank(severity)||x.severity().equalsIgnoreCase(severity)).filter(x->blank(confidence)||x.confidence().equalsIgnoreCase(confidence)).filter(x->blank(repository)||x.repositoryIds().contains(repository)).filter(x->blank(module)||x.moduleIds().contains(module)).filter(x->blank(polarity)||x.polarity().equalsIgnoreCase(polarity)).toList();}

 private void releases(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){boolean bundle=d.releaseRelationships().stream().anyMatch(r->r.type().equals("RELEASE_BUNDLE"));boolean exact=d.compatibility().stream().anyMatch(c->c.status().equals("INCOMPATIBLE"));if(bundle&&(exact||d.releaseRelationships().size()>1))add(out,"RELEASE_LOCKSTEP","Explicit release coordination is combined with cross-repository version alignment evidence.",.88,d.dependencies().stream().filter(x->x.dependencyType().equals("RELEASE_COORDINATION")).toList(),List.of());}
 private void deployments(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){var xs=d.deploymentRelationships().stream().filter(x->x.direction().equals("SOURCE_TO_TARGET")||x.dependencyType().equals("DEPLOYMENT_ORDER")).toList();if(!xs.isEmpty())add(out,"DEPLOYMENT_LOCKSTEP","Explicit deployment ordering or prerequisite relationships connect Product repositories.",.9,xs,List.of());}
 private void cycles(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){Map<String,List<ProductDependencyView>> bySource=d.dependencies().stream().filter(x->!x.targetRepositoryId().isBlank()).collect(Collectors.groupingBy(ProductDependencyView::sourceRepositoryId));Set<String> emitted=new HashSet<>();for(var a:d.dependencies())for(var b:bySource.getOrDefault(a.targetRepositoryId(),List.of()))if(b.targetRepositoryId().equals(a.sourceRepositoryId())){String key=List.of(a.sourceRepositoryId(),a.targetRepositoryId()).stream().sorted().collect(Collectors.joining("|"));if(emitted.add(key))add(out,"CROSS_REPOSITORY_CYCLE","A direct cross-repository dependency cycle is present.",.98,List.of(a,b),List.of(a.dependencyId(),b.dependencyId()));}}
 private void contracts(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){int unknown=d.metrics().unknownCompatibilityCount(),bad=d.metrics().explicitIncompatibilityCount(),ownerless=d.metrics().ownerlessContractCount(),conflicts=d.metrics().ownershipConflictCount();if(unknown+bad+ownerless+conflicts>=2)add(out,"CONTRACT_IMMATURITY","Multiple contract maturity indicators were detected: unknown or incompatible versions and ownership gaps.",bad>0?.92:.75,d.dependencies().stream().filter(x->x.dependencyType().endsWith("_CONTRACT")&&(x.compatibilityStatus().equals("UNKNOWN")||x.compatibilityStatus().equals("INCOMPATIBLE"))).toList(),List.of());}
 private void sharedModels(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){var xs=d.dependencies().stream().filter(x->Set.of("MAVEN_ARTIFACT","SHARED_LIBRARY").contains(x.dependencyType())).filter(x->x.technicalIdentity().toLowerCase().matches(".*(domain|entities|model).*" )).toList();if(xs.size()>=2)add(out,"SHARED_DOMAIN_MODEL","A domain-named internal artifact is referenced across multiple repositories; naming evidence is heuristic.",.62,xs,List.of());}
 private void sharedDatabase(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){var xs=d.dependencies().stream().filter(x->x.dependencyType().equals("SHARED_DATABASE")||x.technicalIdentity().toLowerCase().contains("database")||x.technicalIdentity().toLowerCase().contains("schema")).toList();if(!xs.isEmpty())add(out,"SHARED_DATABASE_OR_SCHEMA","Explicit shared database or schema identity is referenced across repositories.",.95,xs,List.of());}
 private void communication(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){var api=d.dependencies().stream().filter(x->x.dependencyType().equals("API_CONTRACT")).toList();boolean bidirectional=api.stream().anyMatch(a->api.stream().anyMatch(b->a.sourceRepositoryId().equals(b.targetRepositoryId())&&a.targetRepositoryId().equals(b.sourceRepositoryId())));if(bidirectional&&api.size()>=2)add(out,"SYNCHRONOUS_COUPLING","Bidirectional synchronous API dependencies are present across repositories.",.87,api,List.of());var messaging=d.dependencies().stream().filter(x->Set.of("EVENT_CONTRACT","COMMAND_CONTRACT","MESSAGE_CHANNEL").contains(x.dependencyType())).toList();if(messaging.size()>=6&&d.metrics().unknownCompatibilityCount()>0)add(out,"MESSAGING_COUPLING","A broad messaging surface includes unresolved contract compatibility.",.7,messaging,List.of());}
 private void router(ProductDependencyCompositionView d,ProductCompositionView c,List<ProductArchitectureIndicatorView> out){Map<String,List<ProductDependencyView>> routes=d.dependencies().stream().filter(x->Set.of("EVENT_CONTRACT","COMMAND_CONTRACT","MESSAGE_CHANNEL").contains(x.dependencyType())).flatMap(x->java.util.stream.Stream.of(Map.entry(x.sourceRepositoryId(),x),Map.entry(x.targetRepositoryId(),x))).filter(x->!x.getKey().isBlank()).collect(Collectors.groupingBy(Map.Entry::getKey,Collectors.mapping(Map.Entry::getValue,Collectors.toList())));int total=Math.max(1,d.dependencies().size());routes.entrySet().stream().max(Comparator.comparingInt(e->e.getValue().size())).filter(e->e.getValue().size()>=3).ifPresent(e->{double share=(double)e.getValue().size()/total;add(out,"CENTRAL_ROUTER_PRESENT",e.getKey()+" participates in "+e.getValue().size()+" messaging relationships ("+Math.round(share*100)+"% of dependency edges).",Math.min(.95,.6+share/3),e.getValue(),List.of());boolean ownership=d.metrics().ownerlessContractCount()+d.metrics().ownershipConflictCount()>0;if(share>=.5&&ownership)add(out,"CENTRAL_ROUTER_HIGH_COORDINATION_LOAD","Central routing concentration coincides with unclear or conflicting contract ownership.",.78,e.getValue(),List.of());if(share>=.65&&ownership&&d.metrics().unknownCompatibilityCount()+d.metrics().explicitIncompatibilityCount()>1)add(out,"CENTRAL_ROUTER_ESB_DRIFT_RISK","Routing concentration, broad ownership responsibility, and multiple contract compatibility gaps occur together; this indicates drift risk, not a confirmed ESB.",.82,e.getValue(),List.of());});}
 private void boundaries(ProductModels.Product p,ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){Map<String,String> modules=p.repositories().stream().filter(r->r.moduleId()!=null).collect(Collectors.toMap(r->r.id().value(),r->r.moduleId().value()));var crossDependencies=d.dependencies().stream().filter(x->modules.containsKey(x.sourceRepositoryId())&&modules.containsKey(x.targetRepositoryId())&&!modules.get(x.sourceRepositoryId()).equals(modules.get(x.targetRepositoryId()))).toList();long cross=crossDependencies.size();if(p.modules().size()>1&&cross>=Math.max(3,d.dependencies().size()/2))add(out,"PRODUCT_MODULE_BOUNDARY_MISMATCH","A disproportionate share of dependencies crosses explicitly supplied Product Module boundaries.",.72,crossDependencies,List.of());if(p.modules().size()>1&&!d.deploymentRelationships().isEmpty()&&cross>=2)add(out,"PRODUCT_PACKAGING_COUPLING","Cross-module dependencies coincide with explicit deployment relationships, so optional module packaging may require coordinated runtime units.",.7,crossDependencies,List.of());if(p.modules().size()>1&&cross==0)add(out,"INDEPENDENT_MODULES","No mandatory cross-repository dependency was detected across explicitly supplied Product Module boundaries.",.75,List.of(),List.of());}
 private void ownership(ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){if(d.metrics().ownershipConflictCount()+d.metrics().ownerlessContractCount()>=2)add(out,"OWNERSHIP_COUPLING","Multiple cross-repository contracts have missing or conflicting explicit ownership.",.82,List.of(),List.of());}
 private void strengths(ProductModels.Product p,ProductDependencyCompositionView d,List<ProductArchitectureIndicatorView> out){if(p.repositories().size()>1&&d.releaseRelationships().isEmpty())add(out,"INDEPENDENT_VERSIONING","No explicit coordinated release relationship was detected between Product repositories.",.58,List.of(),List.of());if(d.metrics().explicitCompatibilityCoverage()>=80)add(out,"VERSION_COVERAGE","Explicit contract-version coverage is "+d.metrics().explicitCompatibilityCoverage()+"%.",.9,List.of(),List.of());boolean cycle=out.stream().anyMatch(x->x.type().equals("CROSS_REPOSITORY_CYCLE"));if(p.repositories().size()>1&&!cycle)add(out,"ACYCLIC_DEPENDENCIES","No cross-repository dependency cycle was detected in the composed graph.",.85,List.of(),List.of());if(d.metrics().ownerlessContractCount()==0&&d.metrics().ownershipConflictCount()==0&&d.metrics().dependencyCount()>0)add(out,"EXPLICIT_CONTRACT_OWNERSHIP","No missing or conflicting contract ownership was detected.",.76,List.of(),List.of());}
 private List<ProductArchitectureFindingView> aggregate(List<ProductArchitectureIndicatorView> indicators,ProductModels.Product p,long version,double coverage,Instant now){List<ProductArchitectureFindingView> out=new ArrayList<>();for(var i:indicators){boolean strength=Set.of("INDEPENDENT_VERSIONING","VERSION_COVERAGE","ACYCLIC_DEPENDENCIES","EXPLICIT_CONTRACT_OWNERSHIP","INDEPENDENT_MODULES").contains(i.type());String concern=concern(i.type()),severity=strength?"INFO":severity(i.type(),indicators);double raw=Math.max(.2,i.confidence()*coverage),score=Math.round(raw*100d)/100d;List<String> counter=counter(i.type(),indicators);if(!counter.isEmpty())score=Math.max(.2,score-.12);List<String> limits=new ArrayList<>();if(coverage<.8)limits.add("Incomplete Product evidence coverage reduces confidence.");if(i.type().startsWith("CENTRAL_ROUTER"))limits.add("Routing concentration alone does not establish ESB drift or business orchestration.");out.add(new ProductArchitectureFindingView("product-finding-"+UUID.randomUUID(),i.type(),strength?"STRENGTH":"RISK",title(i.type()),i.description(),concern,severity,confidence(score,(int)(coverage*100)),score,List.of(i),List.of(),i.evidenceIds(),i.repositoryIds(),i.moduleIds(),i.dependencyPath().isEmpty()?List.of():List.of(i.dependencyPath()),"Aggregated from explicit Product dependency composition using indicator "+i.type()+".",counter,List.copyOf(limits),version,now));}return List.copyOf(out);}
 private int coverage(ProductModels.Product p,ProductCompositionView c,ProductDependencyCompositionView d,List<ProductArchitectureAnalysisDiagnostic> diagnostics){int repo=p.repositories().size();int discovered=(int)p.repositories().stream().filter(r->!r.discoveryRunIds().isEmpty()).count();int value=repo==0?0:(int)Math.round(discovered*70d/repo)+(c.evidence().isEmpty()?0:15)+(d.dependencies().isEmpty()?0:15);if(discovered<repo)diagnostics.add(new ProductArchitectureAnalysisDiagnostic("analysis-diagnostic-missing-runs","WARNING",(repo-discovered)+" repositories have no associated discovery run.",List.of("repository discovery evidence")));if(!d.diagnostics().isEmpty())diagnostics.add(new ProductArchitectureAnalysisDiagnostic("analysis-diagnostic-partial-dependencies","WARNING","Dependency composition contains unresolved diagnostics.",List.of("complete contract compatibility evidence")));return Math.min(100,value);}
 private String classify(List<ProductArchitectureFindingView> f,int repos,int coverage){if(repos<2||coverage<35)return "INSUFFICIENT_EVIDENCE";long high=f.stream().filter(x->x.polarity().equals("RISK")&&Set.of("HIGH","CRITICAL").contains(x.severity())).count();boolean release=has(f,"RELEASE_LOCKSTEP"),deploy=has(f,"DEPLOYMENT_LOCKSTEP"),cycle=has(f,"CROSS_REPOSITORY_CYCLE");if(release&&deploy&&cycle&&high>=3)return "DISTRIBUTED_MONOLITH_CONFIRMED";if(high>=2&&(release||deploy||cycle))return "DISTRIBUTED_MONOLITH_RISK";long risks=f.stream().filter(x->x.polarity().equals("RISK")).count(),strengths=f.stream().filter(x->x.polarity().equals("STRENGTH")).count();return risks==0?"MODULAR":risks<=strengths?"MOSTLY_MODULAR":"COUPLED";}
 private double assessmentConfidence(List<ProductArchitectureFindingView> f,int coverage){if(f.isEmpty())return coverage/200d;return Math.round(f.stream().mapToDouble(ProductArchitectureFindingView::confidenceScore).average().orElse(0)*coverage)/100d;}
 private void add(List<ProductArchitectureIndicatorView> out,String type,String desc,double confidence,List<ProductDependencyView> deps,List<String> path){var refs=deps.stream().flatMap(x->x.evidence().stream()).toList();out.add(new ProductArchitectureIndicatorView("indicator-"+UUID.randomUUID(),type,desc,confidence,deps.stream().map(ProductDependencyView::dependencyId).distinct().toList(),refs.stream().map(DependencyEvidenceReference::evidenceId).distinct().toList(),deps.stream().flatMap(x->java.util.stream.Stream.of(x.sourceRepositoryId(),x.targetRepositoryId())).filter(x->!x.isBlank()).distinct().toList(),List.of(),path));}
 private static String concern(String t){if(t.contains("RELEASE")||t.equals("INDEPENDENT_VERSIONING"))return "RELEASE_INDEPENDENCE";if(t.contains("DEPLOYMENT")||t.contains("PACKAGING"))return "DEPLOYMENT_INDEPENDENCE";if(t.contains("CONTRACT")||t.equals("VERSION_COVERAGE"))return "CONTRACT_MATURITY";if(t.contains("OWNERSHIP"))return "BOUNDED_OWNERSHIP";if(t.contains("DATABASE"))return "DATA_OWNERSHIP";if(t.contains("ROUTER")||t.contains("MESSAGING")||t.contains("SYNCHRONOUS"))return "COMMUNICATION_COMPLEXITY";return "MODULARITY";}
 private static String severity(String t,List<ProductArchitectureIndicatorView> all){if(Set.of("RELEASE_LOCKSTEP","DEPLOYMENT_LOCKSTEP","CROSS_REPOSITORY_CYCLE","SHARED_DATABASE_OR_SCHEMA","CENTRAL_ROUTER_ESB_DRIFT_RISK").contains(t))return "HIGH";if(t.equals("CENTRAL_ROUTER_HIGH_COORDINATION_LOAD")||t.equals("CONTRACT_IMMATURITY")||t.equals("PRODUCT_PACKAGING_COUPLING"))return "MEDIUM";return "LOW";}
 private static String title(String t){return Arrays.stream(t.split("_")).map(x->x.charAt(0)+x.substring(1).toLowerCase()).collect(Collectors.joining(" "));}
 private static List<String> counter(String t,List<ProductArchitectureIndicatorView> all){List<String>x=new ArrayList<>();if(t.startsWith("CENTRAL_ROUTER")&&!hasIndicator(all,"CENTRAL_ROUTER_HIGH_COORDINATION_LOAD"))x.add("No additional coordination-load indicator was detected; the router may be a thin routing runtime.");if(t.equals("CONTRACT_IMMATURITY")&&hasIndicator(all,"VERSION_COVERAGE"))x.add("Overall explicit contract-version coverage is high.");return x;}
 private static String confidence(double score,int coverage){if(coverage<35)return "INSUFFICIENT_EVIDENCE";if(score>=.95)return "CONFIRMED";if(score>=.8)return "HIGH";if(score>=.6)return "MEDIUM";return "LOW";}
 private static boolean has(List<ProductArchitectureFindingView> xs,String t){return xs.stream().anyMatch(x->x.findingType().equals(t));}private static boolean hasIndicator(List<ProductArchitectureIndicatorView> xs,String t){return xs.stream().anyMatch(x->x.type().equals(t));}
 private static List<String> ids(List<ProductArchitectureFindingView>x,Predicate<ProductArchitectureFindingView> p){return x.stream().filter(p).map(ProductArchitectureFindingView::findingId).toList();}
 private ProductModels.Product requireProduct(String w,String p){return store.find(w,p).orElseThrow(()->new NoSuchElementException("Product not found: "+p));}private static boolean blank(String x){return x==null||x.isBlank();}
 private void emit(ProductModels.Product p,ArchitectureEventType type,String actor,String correlation,Map<String,String> payload){audit.append(new ArchitectureEventEnvelope(null,type,p.workspaceId(),ArchitectureEventSource.PRODUCT_COMPOSITION_SERVICE,Actor.system(blank(actor)?"product-analysis-service":actor),CausationId.newId("product-analysis-command"),new CorrelationId(correlation),null,AuditRelevance.REQUIRED,MutationTarget.NEITHER,payload,null));}
}
