package com.architectureworkbench.api;

/** Immutable Product recommendation vocabulary. Recommendations remain options outside canonical state. */
final class ProductArchitectureRecommendationModels {
 private ProductArchitectureRecommendationModels() {}
 enum Type { CONTRACT_VERSIONING,CONTRACT_OWNERSHIP,RELEASE_DECOUPLING,DEPLOYMENT_DECOUPLING,DEPENDENCY_CYCLE_REDUCTION,SHARED_DOMAIN_MODEL_REDUCTION,SHARED_DATA_OWNERSHIP,SYNCHRONOUS_COUPLING_REDUCTION,MESSAGING_TOPOLOGY_GOVERNANCE,CENTRAL_ROUTER_GOVERNANCE,PRODUCT_MODULE_BOUNDARY_CLARIFICATION,OWNERSHIP_CLARIFICATION,PRODUCT_PACKAGING_DECOUPLING,COMPATIBILITY_MATRIX_INTRODUCTION,OBSERVABILITY_AND_TRACEABILITY,FURTHER_DISCOVERY,NO_CHANGE_REQUIRED }
 enum Status { CANDIDATE,UNDER_REVIEW,ACCEPTED,REJECTED,DEFERRED,SUPERSEDED,IMPLEMENTED,VERIFIED }
 enum Priority { CRITICAL,HIGH,MEDIUM,LOW,INFORMATIONAL }
 enum TimeHorizon { IMMEDIATE,NEXT_RELEASE,NEAR_TERM,MEDIUM_TERM,STRATEGIC,MONITOR }
 enum Estimate { LOW,MEDIUM,HIGH,UNKNOWN }
}
