package com.architectureworkbench.api;
import com.architectureworkbench.api.ApiDtos.*;
import java.util.List;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/workspaces/{workspaceId}/products")
final class ProductController {
 private final ProductCompositionService service; private final ProductDependencyAnalysisService dependencies; private final ProductArchitectureAnalysisService analysis; private final ProductArchitectureRecommendationService recommendations;
 private final com.architectureworkbench.workspace.WorkspaceService workspaces;
 ProductController(ProductCompositionService service,ProductDependencyAnalysisService dependencies,ProductArchitectureAnalysisService analysis,ProductArchitectureRecommendationService recommendations,com.architectureworkbench.workspace.WorkspaceService workspaces){this.service=service;this.dependencies=dependencies;this.analysis=analysis;this.recommendations=recommendations;this.workspaces=workspaces;}
 private void requireWorkspace(String id){workspaces.getWorkspaceGraph(com.architectureworkbench.workspace.WorkspaceId.of(id));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) ProductView create(@PathVariable("workspaceId") String workspaceId,@RequestBody CreateProductRequest request){requireWorkspace(workspaceId);return service.create(workspaceId,request);}
 @GetMapping List<ProductView> list(@PathVariable("workspaceId") String workspaceId){requireWorkspace(workspaceId);return service.list(workspaceId);}
 @GetMapping("/{productId}") ProductView get(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return service.get(workspaceId,productId);}
 @PutMapping("/{productId}") ProductView update(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestBody UpdateProductMetadataRequest request){return service.update(workspaceId,productId,request);}
 @DeleteMapping("/{productId}") @ResponseStatus(HttpStatus.NO_CONTENT) void archive(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){service.archive(workspaceId,productId);}
 @PostMapping("/{productId}/repositories") @ResponseStatus(HttpStatus.CREATED) ProductView addRepository(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestBody AddProductRepositoryRequest request){return service.addRepository(workspaceId,productId,request);}
 @DeleteMapping("/{productId}/repositories/{repositoryId}") ProductView removeRepository(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("repositoryId") String repositoryId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return service.removeRepository(workspaceId,productId,repositoryId,actorRef);}
 @PostMapping("/{productId}/repositories/{repositoryId}/discovery-runs") ProductView attachRun(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("repositoryId") String repositoryId,@RequestBody AttachDiscoveryRunRequest request){return service.attachRun(workspaceId,productId,repositoryId,request);}
 @PostMapping("/{productId}/modules") @ResponseStatus(HttpStatus.CREATED) ProductView createModule(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestBody CreateProductModuleRequest request){return service.createModule(workspaceId,productId,request);}
 @PostMapping("/{productId}/modules/{moduleId}/repositories/{repositoryId}") ProductView assign(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("moduleId") String moduleId,@PathVariable("repositoryId") String repositoryId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return service.assign(workspaceId,productId,moduleId,repositoryId,actorRef);}
 @PostMapping("/{productId}/compose") ProductCompositionView compose(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return service.compose(workspaceId,productId,actorRef);}
 @GetMapping("/{productId}/composition") ProductCompositionView composition(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return service.composition(workspaceId,productId);}
 @GetMapping("/{productId}/relationships") List<ProductRelationshipView> relationships(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return service.composition(workspaceId,productId).relationships();}
 @GetMapping("/{productId}/metrics") ProductCompositionMetrics metrics(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return service.composition(workspaceId,productId).metrics();}
 @PostMapping("/{productId}/dependencies/compose") ProductDependencyCompositionView composeDependencies(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return dependencies.compose(workspaceId,productId,actorRef);}
 @GetMapping("/{productId}/dependencies") List<ProductDependencyView> dependencies(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="type",required=false) String type,@RequestParam(name="repository",required=false) String repository,@RequestParam(name="compatibility",required=false) String compatibility,@RequestParam(name="minimumConfidence",defaultValue="0") double confidence){return dependencies.dependencies(workspaceId,productId,type,repository,compatibility,confidence);}
 @GetMapping("/{productId}/dependency-graph") ProductDependencyGraph graph(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).graph();}
 @GetMapping("/{productId}/compatibility") List<ContractCompatibilityView> compatibility(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).compatibility();}
 @GetMapping("/{productId}/compatibility/matrix") RepositoryCompatibilityMatrix matrix(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){var d=dependencies.latest(workspaceId,productId);var ids=service.get(workspaceId,productId).repositories().stream().map(ProductRepositoryView::repositoryId).toList();var cells=new java.util.ArrayList<RepositoryCompatibilityCell>();for(String a:ids)for(String b:ids){var matches=d.compatibility().stream().filter(x->x.sourceRepositoryId().equals(a)&&x.targetRepositoryId().equals(b)).toList();String status=matches.isEmpty()?"NOT_APPLICABLE":matches.stream().anyMatch(x->x.status().equals("INCOMPATIBLE"))?"INCOMPATIBLE":matches.stream().anyMatch(x->x.status().equals("UNKNOWN"))?"UNKNOWN":"COMPATIBLE";cells.add(new RepositoryCompatibilityCell(a,b,status,matches.size(),matches.stream().map(ContractCompatibilityView::compatibilityId).toList()));}return new RepositoryCompatibilityMatrix(ids,cells);}
 @GetMapping("/{productId}/release-dependencies") List<ReleaseRelationshipView> releases(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).releaseRelationships();}
 @GetMapping("/{productId}/deployment-dependencies") List<ProductDependencyView> deployments(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).deploymentRelationships();}
 @GetMapping("/{productId}/ownership") List<OwnershipRelationshipView> ownership(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).ownershipRelationships();}
 @GetMapping("/{productId}/dependency-metrics") ProductDependencyMetrics dependencyMetrics(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.latest(workspaceId,productId).metrics();}
 @GetMapping("/{productId}/dependency-compositions") List<ProductDependencyCompositionView> dependencyVersions(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return dependencies.versions(workspaceId,productId);}
 @PostMapping("/{productId}/analysis") ProductArchitectureAnalysisView analyse(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return analysis.analyse(workspaceId,productId,actorRef);}
 @GetMapping("/{productId}/analysis") ProductArchitectureAnalysisView latestAnalysis(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return analysis.latest(workspaceId,productId);}
 @GetMapping("/{productId}/analysis/{analysisId}") ProductArchitectureAnalysisView analysis(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("analysisId") String analysisId){return analysis.get(workspaceId,productId,analysisId);}
 @GetMapping("/{productId}/analysis/{analysisId}/findings") List<ProductArchitectureFindingView> findings(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("analysisId") String analysisId,@RequestParam(name="concern",required=false) String concern,@RequestParam(name="findingType",required=false) String type,@RequestParam(name="severity",required=false) String severity,@RequestParam(name="confidence",required=false) String confidence,@RequestParam(name="repository",required=false) String repository,@RequestParam(name="module",required=false) String module,@RequestParam(name="polarity",required=false) String polarity){return analysis.findings(workspaceId,productId,analysisId,concern,type,severity,confidence,repository,module,polarity);}
 @GetMapping("/{productId}/analysis/{analysisId}/findings/{findingId}") ProductArchitectureFindingView finding(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("analysisId") String analysisId,@PathVariable("findingId") String findingId){return analysis.get(workspaceId,productId,analysisId).findings().stream().filter(x->x.findingId().equals(findingId)).findFirst().orElseThrow(()->new java.util.NoSuchElementException("Finding not found: "+findingId));}
 @GetMapping("/{productId}/distributed-monolith-assessment") ProductDistributedMonolithAssessment assessment(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return analysis.latest(workspaceId,productId).assessment();}
 @GetMapping("/{productId}/analysis-history") List<ProductArchitectureAnalysisView> analysisHistory(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return analysis.history(workspaceId,productId);}
 @PostMapping("/{productId}/recommendations/generate") ProductRecommendationGenerationView generateRecommendations(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="actorRef",defaultValue="api-user") String actorRef){return recommendations.generate(workspaceId,productId,actorRef);}
 @GetMapping("/{productId}/recommendations") List<ProductArchitectureRecommendationView> recommendations(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@RequestParam(name="category",required=false) String category,@RequestParam(name="concern",required=false) String concern,@RequestParam(name="priority",required=false) String priority,@RequestParam(name="timeHorizon",required=false) String horizon,@RequestParam(name="status",required=false) String status,@RequestParam(name="repository",required=false) String repository,@RequestParam(name="module",required=false) String module,@RequestParam(name="confidence",required=false) String confidence,@RequestParam(name="findingId",required=false) String findingId){return recommendations.list(workspaceId,productId,category,concern,priority,horizon,status,repository,module,confidence,findingId);}
 @GetMapping("/{productId}/recommendations/{recommendationId}") ProductArchitectureRecommendationView recommendation(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id){return recommendations.get(workspaceId,productId,id);}
 @GetMapping("/{productId}/recommendations/{recommendationId}/alternatives") List<RecommendationAlternativeView> alternatives(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id){return recommendations.get(workspaceId,productId,id).alternatives();}
 @PostMapping("/{productId}/recommendations/{recommendationId}/submit-review") ProductArchitectureRecommendationView submitReview(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id,@RequestBody(required=false) RecommendationActionRequest request){return recommendations.submitReview(workspaceId,productId,id,request);}
 @PostMapping("/{productId}/recommendations/{recommendationId}/defer") ProductArchitectureRecommendationView defer(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id,@RequestBody(required=false) RecommendationActionRequest request){return recommendations.transition(workspaceId,productId,id,"DEFERRED",request);}
 @PostMapping("/{productId}/recommendations/{recommendationId}/reject") ProductArchitectureRecommendationView reject(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id,@RequestBody(required=false) RecommendationActionRequest request){return recommendations.transition(workspaceId,productId,id,"REJECTED",request);}
 @PostMapping("/{productId}/recommendations/{recommendationId}/create-proposed-change") RecommendationProposedChangeView createProposedChange(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId,@PathVariable("recommendationId") String id,@RequestBody(required=false) RecommendationActionRequest request){return recommendations.createProposedChange(workspaceId,productId,id,request);}
 @GetMapping("/{productId}/recommendation-history") List<ProductRecommendationGenerationView> recommendationHistory(@PathVariable("workspaceId") String workspaceId,@PathVariable("productId") String productId){return recommendations.generations(workspaceId,productId);}
}
