package com.architectureworkbench.api;

import com.architectureworkbench.api.ApiDtos.*;
import com.architectureworkbench.audit.*;
import java.time.Instant;
import java.util.*;

final class ProductCompositionService {
 private final ProductRepositoryStore products; private final DiscoveryRunReadRepository runs; private final AuditSink audit;
 ProductCompositionService(ProductRepositoryStore products,DiscoveryRunReadRepository runs,AuditSink audit){this.products=products;this.runs=runs;this.audit=audit;}
 ProductView create(String workspaceId,CreateProductRequest r){var now=Instant.now();var p=new ProductModels.Product(ProductModels.ProductId.create(),workspaceId,new ProductModels.ProductName(r.name()),new ProductModels.ProductDescription(r.description()),ProductModels.ProductStatus.ACTIVE,List.of(),List.of(),new ProductModels.ProductCompositionVersion(0),now,now);products.save(p);emit(p,"PRODUCT_CREATED",r.actorRef(),Map.of("productId",p.id().value(),"name",p.name().value()));return view(p);}
 List<ProductView> list(String w){return products.list(w).stream().map(this::view).toList();}
 ProductView get(String w,String p){return view(product(w,p));}
 ProductView update(String w,String p,UpdateProductMetadataRequest r){var current=product(w,p);var status=parse(ProductModels.ProductStatus.class,r.status(),current.status());return view(products.save(current.withMetadata(new ProductModels.ProductName(r.name()),new ProductModels.ProductDescription(r.description()),status)));}
 void archive(String w,String p){product(w,p);products.delete(w,p);}
 ProductView addRepository(String w,String p,AddProductRepositoryRequest r){var product=product(w,p);for(String run:r.discoveryRunIds()==null?List.<String>of():r.discoveryRunIds()) validateRun(w,run);var repo=new ProductModels.ProductRepository(ProductModels.ProductRepositoryId.create(),r.sourceIdentity(),r.sourceReference(),parse(ProductModels.RepositoryRole.class,r.role(),ProductModels.RepositoryRole.UNKNOWN),null,ProductModels.MembershipStatus.ACTIVE,r.discoveryRunIds(),r.versionMetadata(),r.ownershipMetadata(),Instant.now());var repos=new ArrayList<>(product.repositories());repos.add(repo);var changed=products.save(product.changed(repos,product.modules()));emit(changed,"PRODUCT_REPOSITORY_ADDED",r.actorRef(),Map.of("productId",p,"repositoryId",repo.id().value()));return view(changed);}
 ProductView removeRepository(String w,String p,String id,String actor){var product=product(w,p);var repos=product.repositories().stream().filter(r->!r.id().value().equals(id)).toList();if(repos.size()==product.repositories().size())throw new NoSuchElementException("Product repository not found: "+id);var changed=products.save(product.changed(repos,product.modules()));emit(changed,"PRODUCT_REPOSITORY_REMOVED",actor,Map.of("productId",p,"repositoryId",id));return view(changed);}
 ProductView attachRun(String w,String p,String id,AttachDiscoveryRunRequest request){validateRun(w,request.discoveryRunId());var product=product(w,p);var repos=product.repositories().stream().map(r->r.id().value().equals(id)?r.withRun(request.discoveryRunId()):r).toList();var changed=products.save(product.changed(repos,product.modules()));return view(changed);}
 ProductView createModule(String w,String p,CreateProductModuleRequest r){var product=product(w,p);var module=new ProductModels.ProductModule(ProductModels.ProductModuleId.create(),r.name(),r.description(),parse(ProductModels.ProductModuleType.class,r.type(),ProductModels.ProductModuleType.OTHER),Instant.now());var modules=new ArrayList<>(product.modules());modules.add(module);var changed=products.save(product.changed(product.repositories(),modules));emit(changed,"PRODUCT_MODULE_CREATED",r.actorRef(),Map.of("productId",p,"moduleId",module.id().value()));return view(changed);}
 ProductView assign(String w,String p,String moduleId,String repoId,String actor){var product=product(w,p);if(product.modules().stream().noneMatch(m->m.id().value().equals(moduleId)))throw new NoSuchElementException("Product module not found: "+moduleId);var repos=product.repositories().stream().map(r->r.id().value().equals(repoId)?r.inModule(new ProductModels.ProductModuleId(moduleId)):r).toList();var changed=products.save(product.changed(repos,product.modules()));emit(changed,"PRODUCT_REPOSITORY_ASSIGNED_TO_MODULE",actor,Map.of("productId",p,"moduleId",moduleId,"repositoryId",repoId));return view(changed);}
 ProductCompositionView compose(String w,String p,String actor){var product=product(w,p);var evidence=new ArrayList<ProductEvidenceItem>();var observations=new ArrayList<ProductObservationItem>();var metrics=new ArrayList<ProductMetricItem>();var contributions=new ArrayList<RepositoryEvidenceContribution>();var diagnostics=new ArrayList<ProductCompositionDiagnostic>();Set<String> runIds=new LinkedHashSet<>();
  for(var repo:product.repositories()) for(String runId:repo.discoveryRunIds()){if(!runIds.add(runId))continue;var d=runs.findById(w,runId);if(d.isEmpty()){diagnostics.add(new ProductCompositionDiagnostic("missing-run-"+runId,"WARNING","Discovery run is unavailable: "+runId,List.of(repo.id().value()),List.of()));continue;}var run=d.get();contributions.add(new RepositoryEvidenceContribution(repo.id().value(),repo.sourceIdentity(),runId,run.evidence().size(),run.observations().size(),run.metrics().size()));for(var e:run.evidence())evidence.add(new ProductEvidenceItem("product-evidence-"+evidence.size(),repo.id().value(),repo.sourceIdentity(),runId,e));for(var o:run.observations())observations.add(new ProductObservationItem("product-observation-"+observations.size(),repo.id().value(),runId,o));for(var m:run.metrics())metrics.add(new ProductMetricItem("product-metric-"+metrics.size(),repo.id().value(),runId,m));}
  var resolution=resolve(evidence);var relationships=relationships(resolution.identities,evidence);double owner=percent(product.repositories().stream().filter(r->!r.ownershipMetadata().isEmpty()).count(),product.repositories().size());double module=percent(product.repositories().stream().filter(r->r.moduleId()!=null).count(),product.repositories().size());var contracts=evidence.stream().filter(x->identity(x.evidence())!=null&&Set.of("CONTRACT","EVENT","COMMAND").contains(identity(x.evidence()).type)).toList();long versioned=contracts.stream().filter(x->version(x.evidence()).isPresent()).count();double versions=percent(versioned,contracts.size());int sharedContracts=(int)resolution.identities.stream().filter(x->x.identityType().contains("CONTRACT")||x.identityType().equals("EVENT")||x.identityType().equals("COMMAND")).count();int channels=(int)resolution.identities.stream().filter(x->x.identityType().equals("CHANNEL")).count();var summary=new ProductCompositionMetrics(product.repositories().size(),product.modules().size(),runIds.size(),evidence.size(),relationships.size(),sharedContracts,channels,resolution.conflicts.size(),owner,versions,module);var result=new ProductCompositionView(p,w,product.compositionVersion().value(),Instant.now(),contributions,evidence,observations,metrics,resolution.identities,resolution.conflicts,relationships,summary,diagnostics);products.saveComposition(w,p,result);emit(product,"PRODUCT_COMPOSITION_GENERATED",actor,Map.of("productId",p,"evidenceCount",String.valueOf(evidence.size()),"relationshipCount",String.valueOf(relationships.size())));return result; }
 ProductCompositionView composition(String w,String p){product(w,p);return products.composition(w,p).orElseThrow(()->new NoSuchElementException("Product composition not generated: "+p));}
 private Resolution resolve(List<ProductEvidenceItem> items){Map<String,List<ProductEvidenceItem>> exact=new LinkedHashMap<>();Map<String,List<ProductEvidenceItem>> simple=new LinkedHashMap<>();for(var i:items){var id=identity(i.evidence());if(id!=null){exact.computeIfAbsent(id.type+"|"+id.value+"|"+id.version,k->new ArrayList<>()).add(i);if(id.simpleName!=null)simple.computeIfAbsent(id.type+"|"+id.simpleName,k->new ArrayList<>()).add(i);}}var identities=new ArrayList<CrossRepositoryIdentity>();for(var e:exact.entrySet()){var repos=e.getValue().stream().map(ProductEvidenceItem::repositoryId).distinct().toList();if(repos.size()>1){var parts=e.getKey().split("\\|",-1);identities.add(new CrossRepositoryIdentity("identity-"+identities.size(),parts[0],parts[1],parts[2],"EXACT",1.0,repos,e.getValue().stream().map(ProductEvidenceItem::productEvidenceId).toList()));}}var conflicts=new ArrayList<IdentityConflict>();for(var e:simple.entrySet()){var repos=e.getValue().stream().map(ProductEvidenceItem::repositoryId).distinct().toList();var values=e.getValue().stream().map(x->identity(x.evidence())).filter(Objects::nonNull).map(x->x.value+"@"+x.version).distinct().toList();if(repos.size()>1&&values.size()>1)conflicts.add(new IdentityConflict("conflict-"+conflicts.size(),"SIMPLE_NAME",""+e.getKey(),"Similar technical names have different qualified identities or versions; no merge was performed.",0.55,repos,e.getValue().stream().map(ProductEvidenceItem::productEvidenceId).toList()));}return new Resolution(identities,conflicts);}
 private List<ProductRelationshipView> relationships(List<CrossRepositoryIdentity> ids,List<ProductEvidenceItem> evidence){var out=new ArrayList<ProductRelationshipView>();for(var id:ids)for(int i=0;i<id.repositoryIds().size();i++)for(int j=i+1;j<id.repositoryIds().size();j++)out.add(new ProductRelationshipView("relationship-"+out.size(),id.identityType().equals("CHANNEL")?"SHARED_CHANNEL":"SHARED_IDENTITY",id.repositoryIds().get(i)+" and "+id.repositoryIds().get(j)+" reference "+id.canonicalValue(),id.repositoryIds().get(i),id.repositoryIds().get(j),id.canonicalValue()+(id.explicitVersion().isBlank()?"":" v"+id.explicitVersion()),id.confidence(),id.productEvidenceIds()));return out;}
 private Identity identity(DiscoveryEvidenceView e){var a=e.attributes();String contract=first(a.get("contractId"),a.get("eventName"),a.get("commandName"));String type=a.containsKey("eventName")?"EVENT":a.containsKey("commandName")?"COMMAND":contract.isBlank()?"": "CONTRACT";if(!contract.isBlank())return new Identity(type,contract,version(e).orElse(""),simple(contract));String channel=first(a.get("channelName"),a.get("queueName"),a.get("destination"));if(!channel.isBlank())return new Identity("CHANNEL",channel,"",channel);String coordinates=first(a.get("coordinates"),a.get("groupId")+":"+a.get("artifactId"));if(!coordinates.isBlank()&&!coordinates.contains("null"))return new Identity("MAVEN_COORDINATES",coordinates,"",coordinates);String operation=a.getOrDefault("operationId","");if(!operation.isBlank())return new Identity("OPENAPI_OPERATION",operation,"",operation);String pkg=a.getOrDefault("packageName","");return pkg.isBlank()?null:new Identity("PACKAGE_NAMESPACE",pkg,"",simple(pkg));}
 private Optional<String> version(DiscoveryEvidenceView e){return Optional.ofNullable(first(e.attributes().get("contractVersion"),e.attributes().get("version"),e.attributes().get("schemaVersion"),e.attributes().get("apiVersion"))).filter(x->!x.isBlank());}
 private record Identity(String type,String value,String version,String simpleName){} private record Resolution(List<CrossRepositoryIdentity> identities,List<IdentityConflict> conflicts){}
 private ProductModels.Product product(String w,String p){return products.find(w,p).orElseThrow(()->new NoSuchElementException("Product not found: "+p));} private void validateRun(String w,String r){if(runs.findById(w,r).isEmpty())throw new NoSuchElementException("Discovery run not found: "+r);}
 private ProductView view(ProductModels.Product p){return new ProductView(p.id().value(),p.workspaceId(),p.name().value(),p.description().value(),p.status().name(),p.compositionVersion().value(),p.createdAt(),p.updatedAt(),p.repositories().stream().map(r->new ProductRepositoryView(r.id().value(),r.sourceIdentity(),r.sourceReference(),r.role().name(),r.moduleId()==null?null:r.moduleId().value(),r.status().name(),r.discoveryRunIds(),r.versionMetadata(),r.ownershipMetadata(),r.addedAt())).toList(),p.modules().stream().map(m->new ProductModuleView(m.id().value(),m.name(),m.description(),m.type().name(),m.createdAt())).toList());}
 private void emit(ProductModels.Product p,String type,String actor,Map<String,String> payload){ArchitectureEventType eventType=ArchitectureEventType.valueOf(type);Map<String,String> typed=switch(eventType){case PRODUCT_CREATED->new ProductArchitectureEvents.ProductCreated(payload.get("productId"),payload.get("name")).payload();case PRODUCT_REPOSITORY_ADDED->new ProductArchitectureEvents.ProductRepositoryAdded(payload.get("productId"),payload.get("repositoryId")).payload();case PRODUCT_REPOSITORY_REMOVED->new ProductArchitectureEvents.ProductRepositoryRemoved(payload.get("productId"),payload.get("repositoryId")).payload();case PRODUCT_MODULE_CREATED->new ProductArchitectureEvents.ProductModuleCreated(payload.get("productId"),payload.get("moduleId")).payload();case PRODUCT_REPOSITORY_ASSIGNED_TO_MODULE->new ProductArchitectureEvents.ProductRepositoryAssignedToModule(payload.get("productId"),payload.get("moduleId"),payload.get("repositoryId")).payload();case PRODUCT_COMPOSITION_GENERATED->new ProductArchitectureEvents.ProductCompositionGenerated(payload.get("productId"),Integer.parseInt(payload.get("evidenceCount")),Integer.parseInt(payload.get("relationshipCount"))).payload();default->payload;};audit.append(new ArchitectureEventEnvelope(null,eventType,p.workspaceId(),ArchitectureEventSource.PRODUCT_COMPOSITION_SERVICE,Actor.system(actor==null||actor.isBlank()?"product-service":actor),CausationId.newId("product-command"),CorrelationId.newId("product"),null,AuditRelevance.REQUIRED,MutationTarget.NEITHER,typed,null));}
 private static <E extends Enum<E>>E parse(Class<E> t,String v,E d){try{return v==null?d:Enum.valueOf(t,v.toUpperCase(Locale.ROOT));}catch(Exception e){return d;}}private static double percent(long n,long d){return d==0?0d:Math.round(n*10000d/d)/100d;}private static String simple(String s){int i=Math.max(s.lastIndexOf('.'),s.lastIndexOf('/'));return i<0?s:s.substring(i+1);}private static String first(String...v){for(String x:v)if(x!=null&&!x.isBlank())return x;return "";}
}
